#Análise de Dados no Varejo com NumPy

In [1]:
import numpy as np

##Nível 1: Básico — Faturamento Semanal e Filtros

**Passo 1**: Crie um array unidimensional chamado pecas_vendidas contendo o histórico diário da semana: [150, 120, 90, 210, 300, 250, 180] utilizando a função np.array().

In [5]:
pecas_vendidas = np.array([150, 120, 90, 210, 300, 250, 180])
print(pecas_vendidas)

[150 120  90 210 300 250 180]


**Passo 2**: A gerência pediu uma estimativa rápida de faturamento. Sabendo que o preço médio de cada peça é de R$ 50,00, crie um novo array multiplicando o array original por 50. Observe como o NumPy aplica essa operação matemática a todos os elementos de uma só vez, sem a necessidade de escrever laços de repetição (operações vetorizadas).

In [3]:
novo_array = pecas_vendidas * 50
print(novo_array)

[ 7500  6000  4500 10500 15000 12500  9000]


**Passo 3**: Identifique os dias de pico. Crie uma máscara booleana para filtrar e extrair apenas os dias em que a loja vendeu estritamente mais de 200 peças (ex: pecas_vendidas > 200).


In [7]:
mascara = pecas_vendidas > 200
print(pecas_vendidas[mascara])

[210 300 250]


##Nível 2: Intermediário — Múltiplas Filiais e Falhas de Sistema

**Passo 1**: Crie uma matriz 2D a partir das seguintes listas para representar as vendas:
Loja A: [200, 220, np.nan, 250] (Houve uma falha no sistema no 3º dia, gerando um valor não-número).
Loja B: [150, 180, 160, 190]
Loja C: [300, 310, 290, 330]

In [8]:
vendas = np.array([[200, 220, np.nan, 250], [150, 180, 160, 190], [300, 310, 290, 330]])

**Passo 2**: Calcule o total de peças vendidas por cada loja (agregando pelas linhas). Para isso, aplique a função de soma especificando o parâmetro axis=1.


In [11]:
total_por_loja = np.nansum(vendas, axis=1)
print(total_por_loja)

[ 670.  680. 1230.]


**Passo 3**: A diretoria quer saber a média diária geral da rede. Como os dados reais frequentemente possuem lacunas, calcule a média utilizando a função do NumPy que ignora os valores nan. Se você usar a média normal, o resultado será contaminado e invalidará o relatório.

In [12]:
media_diaria = np.nanmean(vendas)
print(media_diaria)

234.54545454545453


**Passo 4**: A meta diária de cada loja é vender 200 peças. Utilize a função np.where() para criar uma nova matriz condicional, onde os valores maiores ou iguais a 200 sejam substituídos pelo texto 'Meta Atingida', e os valores inferiores sejam substituídos por 'Abaixo'.

In [13]:
meta = np.where(vendas >= 200, 'Meta Atingida', 'Abaixo')
print(meta)

[['Meta Atingida' 'Meta Atingida' 'Abaixo' 'Meta Atingida']
 ['Abaixo' 'Abaixo' 'Abaixo' 'Abaixo']
 ['Meta Atingida' 'Meta Atingida' 'Meta Atingida' 'Meta Atingida']]


##Nível 3: Avançado — Categorização e Destaques de Marketing

**Passo 1**: Para simular uma base de clientes, utilize o gerador moderno com uma semente fixa (np.random.default_rng()) para que os resultados sejam reproduzíveis. Crie uma amostra com 50 vendas sorteadas entre as opções ['Eletrônicos', 'Roupas', 'Casa'].

In [14]:
clientes = np.random.default_rng().choice(['Eletrônicos', 'Roupas', 'Casa'], size=50)
print(clientes)

['Eletrônicos' 'Casa' 'Roupas' 'Eletrônicos' 'Casa' 'Roupas' 'Casa'
 'Roupas' 'Eletrônicos' 'Casa' 'Roupas' 'Roupas' 'Roupas' 'Eletrônicos'
 'Roupas' 'Eletrônicos' 'Eletrônicos' 'Eletrônicos' 'Roupas' 'Eletrônicos'
 'Roupas' 'Roupas' 'Roupas' 'Roupas' 'Roupas' 'Roupas' 'Roupas'
 'Eletrônicos' 'Casa' 'Eletrônicos' 'Eletrônicos' 'Casa' 'Eletrônicos'
 'Eletrônicos' 'Casa' 'Casa' 'Roupas' 'Casa' 'Casa' 'Casa' 'Eletrônicos'
 'Casa' 'Eletrônicos' 'Roupas' 'Casa' 'Roupas' 'Roupas' 'Roupas' 'Roupas'
 'Eletrônicos']


**Passo 2**: Determine o volume de vendas de cada departamento. Utilize a função np.unique habilitando o argumento return_counts=True para obter os valores únicos e suas respectivas contagens — esta é uma forma rápida de fazer o equivalente numérico de contagem de categorias.

In [15]:
volume_de_vendas = np.unique(clientes, return_counts=True)
print(volume_de_vendas)

(array(['Casa', 'Eletrônicos', 'Roupas'], dtype='<U11'), array([13, 16, 21]))


**Passo 3**: O time de marketing enviou um array com o faturamento de cinco campanhas simultâneas: [12000, 45000, 23000, 89000, 31000]. Identifique rapidamente a campanha campeã utilizando o método que retorna o índice (posição) do maior valor do array.

In [20]:
campanhas = np.array([12000, 45000, 23000, 89000, 31000])
campanha_campeã = np.argmax(campanhas)
campanha_campeã

np.int64(3)

#Organização e Transformação de Dados com NumPy

##Nível 1: Básico — Geração de Sequências e Tipagem de Dados

**Passo 1**: Crie um array representando os 30 dias de um mês de faturamento utilizando a função np.arange(1, 31).

In [21]:
faturamento = np.arange(1, 31)
print(faturamento)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


**Passo 2**: Simule 5 metas de vendas igualmente espaçadas entre RS  20.000 e R$ 30.000 para uma equipe ao longo da semana utilizando a função np.linspace(20000, 30000, 5).

In [22]:
metas_de_vendas = np.linspace(20000, 30000, 5)
print(metas_de_vendas)

[20000. 22500. 25000. 27500. 30000.]


**Passo 3**: O sistema de logística exportou a contagem de estoque físico como números decimais (ex: np.array([10.5, 20.1, 30.9])). Converta este array diretamente para números inteiros utilizando o método .astype(int).

In [23]:
estoque_fisico = np.array([10.5, 20.1, 30.9])
estoque_fisico = estoque_fisico.astype(int)
print(estoque_fisico)

[10 20 30]


**Passo 4**: A partir do array de dias do mês criado no Passo 1, capture os últimos 5 dias e inverta a ordem (do mais recente para o mais antigo) através do fatiamento com passo negativo [::-1].

In [27]:
fatia = faturamento[-5:][::-1].copy()
print(fatia)

[30 29 28 27 26]


##Nível 2: Intermediário — Redimensionamento e Proteção de Dados

**Passo 1**: Você recebeu um array unidimensional com o total de visitas de um portal em 12 meses. Utilize o método .reshape(4, 3) para reorganizar automaticamente esses elementos em uma matriz de 4 trimestres (4 linhas e 3 colunas).

In [28]:
visitas = np.array([100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650])
visitas = visitas.reshape(4, 3)
print(visitas)

[[100 150 200]
 [250 300 350]
 [400 450 500]
 [550 600 650]]


**Passo 2**: A equipe de marketing enviou os dados do primeiro semestre e a equipe comercial enviou os do segundo semestre. Combine essas duas matrizes empilhando-as verticalmente com a função np.vstack().

In [32]:
semestres = np.vstack((visitas[:2], visitas[2:]))
print(semestres)

[[100 150 200]
 [250 300 350]
 [400 450 500]
 [550 600 650]]


**Passo 3**: Extraia apenas o primeiro trimestre da matriz para criar um cenário de projeção no Google Colab. Para evitar a "pegadinha" onde alterar a nova fatia modifica o array original por acidente, utilize o método .copy() no momento do fatiamento.

In [34]:
projecao = semestres[:1].copy()
print(projecao)

[[100 150 200]]


**Passo 4**: Para exportar os dados estruturados de volta para um formato de relatório corrido, utilize o método ravel() para achatar a matriz bidimensional de volta em um array 1D.

In [36]:
exportar = visitas.ravel()
print(exportar)

[100 150 200 250 300 350 400 450 500 550 600 650]


##Nível 3: Avançado — Ranking, Broadcasting e Resolução de Sistemas

**Passo 1**: Você possui as seguintes pontuações de alunos em uma avaliação de pensamento computacional: np.array([85, 92, 78, 95, 88]). Em vez de apenas ordenar os valores, utilize np.argsort() para obter os índices dessa ordenação, permitindo descobrir rapidamente a posição de cada aluno no ranking geral.

In [37]:
pontuacoes = np.array([85, 92, 78, 95, 88])
ranking = np.argsort(pontuacoes)
print(ranking)

[2 0 4 1 3]


**Passo 2**: Você possui um vetor contendo preços base em formato de linha. Insira uma nova dimensão neste vetor utilizando np.newaxis para transformá-lo estruturalmente em uma coluna. Isso prepara a matriz para cruzar e aplicar múltiplos percentuais de desconto simultaneamente via regras de broadcasting.

In [38]:
preco = np.array([100, 150, 200])
preco = preco[:, np.newaxis]
print(preco)

[[100]
 [150]
 [200]]


**Passo 3**: Descubra o custo unitário exato de dois recursos de hardware para um laboratório. O projeto A usou 2 placas robóticas e 1 sensor, custando RS 500 no total. O projeto B usou 1 placa robótica e devolveu 1 sensor (estorno), custando R$ 100 no total. Crie a matriz de coeficientes A e o vetor de resultados b, aplicando a função np.linalg.solve(A, b) para encontrar os valores individuais das peças sem realizar o cálculo manual.

In [40]:
matriz_de_coeficientes = np.array([[2, 1], [1, -1]])
vetor_de_resultados = np.array([500, 100])
solucao = np.linalg.solve(matriz_de_coeficientes, vetor_de_resultados)
print(solucao)

[200. 100.]
